# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/kane/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    bootloader \
    keystorage \
    ldfw \
    logo \
    modem
