# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/kane/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/kane

PRODUCT_COPY_FILES += \
    vendor/motorola/kane/proprietary/vendor/etc/ap_gain_mmul.bin:$(TARGET_COPY_OUT_VENDOR)/etc/ap_gain_mmul.bin \
    vendor/motorola/kane/proprietary/vendor/etc/dolby/dax-default.xml:$(TARGET_COPY_OUT_VENDOR)/etc/dolby/dax-default.xml \
    vendor/motorola/kane/proprietary/vendor/etc/sec_s3nrn81_rfreg.bin:$(TARGET_COPY_OUT_VENDOR)/etc/sec_s3nrn81_rfreg.bin \
    vendor/motorola/kane/proprietary/vendor/etc/sim_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/sim_configuration.xml \
    vendor/motorola/kane/proprietary/vendor/firmware/fimc_is_lib.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_lib.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/fimc_is_rta.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/fimc_is_rta.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/himax-hix83112a-hx83112a-0C00-208-kane.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/himax-hix83112a-hx83112a-0C00-208-kane.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/novatek_ts-nov36672a-NT36672A-190108-04-kane.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts-nov36672a-NT36672A-190108-04-kane.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/os.checked_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/os.checked_0.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/os.checked_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/os.checked_1.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/os.checked_2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/os.checked_2.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/os.checked_3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/os.checked_3.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/os.checked_4.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/os.checked_4.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/os.checked_5.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/os.checked_5.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/os.checked_6.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/os.checked_6.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/os.checked_7.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/os.checked_7.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/os.checked_8.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/os.checked_8.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/setfile_2p7sq.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_2p7sq.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/setfile_2t7sx.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_2t7sx.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/setfile_2x5sp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_2x5sp.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/setfile_5e9.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_5e9.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/setfile_6b2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_6b2.bin \
    vendor/motorola/kane/proprietary/vendor/firmware/setfile_gm1sp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/setfile_gm1sp.bin

PRODUCT_PACKAGES += \
    camera.exynos9610 \
    sensors.kane_sprout \
    libdapparamstorage \
    libexynoscamera3 \
    libhwjpeg_vendor \
    libril_sitril \
    libsitril-audio \
    libsitril-client \
    libsitril-gps \
    libsitril-ims \
    libsitril-nr \
    libsitril-psensor \
    libsitril-sar \
    libsitril-se \
    libsitril-wlan \
    libsitril \
    sensors.chub \
    vendor.samsung_slsi.telephony.hardware.oemservice@1.0 \
    vendor.samsung_slsi.telephony.hardware.radio@1.0 \
    vendor.samsung_slsi.telephony.hardware.radio@1.1 \
    vendor.samsung_slsi.telephony.hardware.radioExternal@1.0 \
    vendor.samsung_slsi.telephony.hardware.radioExternal@1.1 \
    audio.primary.exynos9610 \
    libalsautils_sec \
    libaudio-ril \
    libaudioproxy \
    libmotaudioutils \
    libunshorten \
    libadropbox \
    cbd \
    rild_exynos \
    main_abox
